// ===================================================================
// Library Type Definitions
// ===================================================================

/**
 * Represents a document in the library
 */
export interface LibraryDocument {
  id: string;
  filePath: string;
  title: string;
  author?: string;
  pageCount: number;
  thumbnail?: string; // base64 image data

  // Reading state
  lastOpened?: Date;
  dateAdded: Date;
  currentPage: number;
  readingProgress: number; // 0-1

  // Organization
  collections: string[];
  tags: string[];
  isFavorite: boolean;
  color?: string;

  // AI metadata
  summary?: string;
  topics: string[]; // extracted topics
  embeddingId?: string; // for vector search

  // Stats
  timeSpentReading: number; // seconds
  highlightCount: number;
}

/**
 * Represents a collection/folder
 */
export interface Collection {
  id: string;
  name: string;
  color?: string;
  icon?: string;
  documentIds: string[];
  isAutoGenerated?: boolean; // AI-created collection
  createdAt: Date;
}

/**
 * Library view options
 */
export type LibraryViewMode = 'grid' | 'list';

/**
 * Sort options for library
 */
export type LibrarySortBy = 'recent' | 'title' | 'dateAdded' | 'progress';

/**
 * Filter options for library
 */
export interface LibraryFilters {
  collectionId?: string;
  tags?: string[];
  isFavorite?: boolean;
  searchQuery?: string;
}

/**
 * Library state
 */
export interface LibraryState {
  documents: LibraryDocument[];
  collections: Collection[];
  viewMode: LibraryViewMode;
  sortBy: LibrarySortBy;
  filters: LibraryFilters;
}
